### ISSUE TITLE
Compiling plugin in Lion

### ISSUE THREAD

**Issue by imehr** [mirek/quartzcomposer-websocket#1]
Hi,
Just wanted to try your plugin, I tried to compile the code but it shows two error when I want to build the project.

Here is a screenshot of the error message.
https://skitch.com/e-mehran/fse76/quartzcomposer-websocket
I was wondering if you have a compiled plugin for Lion to share?
I think this is a great plugin, I watch the video on youtube(http://www.youtube.com/watch?v=L8GQgSHecNk&sns=tw), loog great.

Cheers,
Mehran

**Comment by mirek** [comment]
tested on mountain lion, works fine.
