### ISSUE TITLE
Quartz WebSocket on OSX 10.8.2

### ISSUE THREAD

**Issue by dskvr** [mirek/quartzcomposer-websocket#4]
I followed the installation instructions contained within readme. I built the plugin, there were 2 alerts from the YAJL library, semantic issues, but nothing that should cripple the build. Dropped the plugin in the "/Library/Graphics/Quartz Composer Plugins" directory (I tried the patches directory as well, JIC). Loaded up the example Composition and the WebSocket (WS) patch was in the Library. Configured the patch in the settings panel of the inspector. Opened the example html in Chrome, and to my dismay, after much tinkering, was unable to connect to the WS. 

Your Javascript looked right, so I tested a known WS, and sure enough the example worked. I could not get any events to fire, other than the 'onclose' event by closing the Quartz Composition containing the actie WS. This confused me, how could a WS close if a connection was never opened? 

It left me to debugging the WebSocket, and not being incredibly familiar with Objective-C, I fell short of solving the problem. I tried different ports with the same results. Do you have any insight, such as hints, tips or suggestions to getting this working? Thank you so much for any information, I really appreciate the potential of this plugin!

**Comment by mirek** [comment]
thanks, when this plugin was written there was no websocket standard yet, it was based on protocol drafts. now the protocol is standarized (rfc6455) and the code needs to be updated to support it, will have a look.

**Comment by dskvr** [comment]
:)

**Comment by mirek** [comment]
try now, it seems to work on current safari/chrome/firefox. when updating your repo don't forget to pull it recursively so it picks submodule changes.
