### ISSUE TITLE
Will not connect in 10.10

### ISSUE THREAD

**Issue by ihorner** [mirek/quartzcomposer-websocket#5]
Whether downloading from precompiled builds, or building from source, I can't get Quartz Composer to go online with a websockets server.

Any chance you could assist in getting this up and running in Yosemite?

**Comment by designerfuzzi** [comment]
Compiled in xcode 6.3 osx sdk 10.9, turned off ARC with 'unsupported' and no code change it workes in yosemite here. So be sure to check your firewall and be prepared to answer correct when the system is asking you if any request from the net is allowed to go into quartz composer or not. The example is sending on port 60001

**Comment by ihorner** [comment]
You are correct designerfuzzi, I managed to get it to compile and works mostly, but ran into the same issues you did in issue #6 with the doublets and the check box.
